# Maestro configuration for Sentry data generation
flows:
  # Essential user behavior simulation
  - user-behaviors/comprehensive-user-simulation.yml
  # Error behavior simulation
  - user-behaviors/error-simulation.yml

# Global test settings
tags:
  - e2e
  - skipline
  - sentry-data
  
# Environment-specific settings
environments:
  - name: production
    appId: com.sergical.skipline
    vars:
      API_URL: https://skipline-backend.onrender.com
